// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package aufzug.java.lang;

import aufzug.java.lang;

/************************************************************/
/**
 * 
 */
public class Exception {
};
