// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package aufzug.ShoppingCenter;

/************************************************************/
/**
 * 
 */
public class Aufzug {
	/**
	 * 
	 */
	public unlimitednatural NumberOfPassengers;
	/**
	 * 
	 */
	public int WeightLimit;
	/**
	 * 
	 */
	public Etage CurrentFloor;
	/**
	 * 
	 */
	public DoorState Door;

	/**
	 * 
	 * @param numberOfFloors 
	 * @return 
	 */
	public Fahrgast[] moveUp(unlimitednatural numberOfFloors) {
	}

	/**
	 * 
	 * @param numberOfFloors 
	 * @return 
	 */
	public Fahrgast[] moveDown(unlimitednatural numberOfFloors) {
	}

	/**
	 * 
	 */
	public void openDoors() {
		Door = DoorState.Opening;
		Door = DoorState.Open;
	}

	/**
	 * 
	 */
	public void closeDoors() {
		Door = DoorState.Closing;
		Door = DoorState.Closed;
	}
};
