// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package aufzug.ShoppingCenter;

/************************************************************/
/**
 * 
 */
public enum DoorState {
	/**
	 * 
	 */
	Open,
	/**
	 * 
	 */
	Opening,
	/**
	 * 
	 */
	Closing,
	/**
	 * 
	 */
	Closed;
};
