// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package aufzug.ShoppingCenter;

/************************************************************/
/**
 * 
 */
public class Fahrgast {
	/**
	 * 
	 */
	public float Weight;
	/**
	 * 
	 */
	public Etage Destination;
};
