// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package aufzug;

import aufzug.DoorState;
import aufzug.Etage;
import aufzug.Fahrgast;
import aufzug.ShoppingCenter;

/************************************************************/
/**
 * 
 */
public class Aufzug {
	/**
	 * 
	 */
	public unlimitednatural NumberOfPassengers;
	/**
	 * 
	 */
	public Fahrgast[] Passengers;
	/**
	 * 
	 */
	public int WeightLimit;
	/**
	 * 
	 */
	public Etage CurrentFloor;
	/**
	 * 
	 */
	public DoorState Door;

	/**
	 * 
	 * @param numberOfFloors 
	 * @return 
	 */
	public Fahrgast[] moveUp(unlimitednatural numberOfFloors) {
	}

	/**
	 * 
	 * @param numberOfFloors 
	 * @return 
	 */
	public Fahrgast[] moveDown(unlimitednatural numberOfFloors) {
	}

	/**
	 * 
	 */
	public void openDoors() {
	}

	/**
	 * 
	 */
	public void closeDoors() {
	}
};
