// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package aufzug;

/************************************************************/
/**
 * 
 */
public class Aufzug {
	/**
	 * 
	 */
	public unlimitednatural NumberOfPassengers;
	/**
	 * 
	 */
	public Fahrgast[] Passengers;
	/**
	 * 
	 */
	public int WeightLimit = 2400;
	/**
	 * 
	 */
	public Etage CurrentFloor;
	/**
	 * 
	 */
	public DoorState Door = Closed;

	/**
	 * 
	 * @return 
	 * @param numberOfFloors 
	 */
	public Fahrgast[] moveUp(unlimitednatural numberOfFloors) throws InvalidDoorState {
	}

	/**
	 * 
	 * @return 
	 * @param numberOfFloors 
	 */
	public Fahrgast[] moveDown(unlimitednatural numberOfFloors) throws InvalidDoorState {
	}

	/**
	 * 
	 */
	public void openDoors() {
	}

	/**
	 * 
	 */
	public void closeDoors() {
	}
};
