// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package aufzug;

/************************************************************/
/**
 * 
 */
public class DoorStillOpen extends java.lang.Exception {
};
