// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package aufzug;

/************************************************************/
/**
 * 
 */
public class Etage {
	/**
	 * 
	 */
	public int Number;
	/**
	 * 
	 */
	public String Name;
	/**
	 * 
	 */
	public aufzug.Etage Next;
	/**
	 * 
	 */
	public aufzug.Etage Previous;
};
