// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package aufzug;

import aufzug.ShoppingCenter;

/************************************************************/
/**
 * 
 */
public class Exception {
};
