// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package aufzug.ShoppingCenter.Exception;

/************************************************************/
/**
 * 
 */
public class InvalidDoorState extends Exception {
};
